### ISSUE TITLE
StandardJS 

### ISSUE THREAD

**Issue by oferitz** [RebirthDB/rebirthdb-desktop#12]
Set up standard.js as linter. we need to make sure it works nicely with Prettier (might require some non-trivial settings)

**Comment by grandquista** [comment]
I have started on this task. Most of the challenge so far has been around existing pieces of the build infrastructure. Is `yarn run test-all` intended to be the correct place to add this check?

**Comment by oferitz** [comment]
Thanks for taking this. see also my comment to your PR [here](https://github.com/RebirthDB/rebirthdb-desktop/pull/23)

`test-all` is not implemented yet, we only use `test` for now.

You are right that this is a bit challenging and there should be a clear separation what each tool is responsible for. Standard should not affect any styling rules like indentation and quoting and should only serve as a JS linter.

**Comment by oferitz** [comment]
https://github.com/sheerun/prettier-standard
