### ISSUE TITLE
Merge stratagey

### ISSUE THREAD

**Issue by sagivf** [RebirthDB/rebirthdb-desktop#22]
When it is possible and not to much of a hassle can we try and reabse and past-forward merges to master?
I don't like all the extra commit entries and tree divergence when it's a non conflicting or feature pull request. I'm not sure how to do this is done in github though...

**Comment by oferitz** [comment]
Do you mean like this?

<img width="334" alt="screen shot 2018-05-26 at 6 45 12" src="https://user-images.githubusercontent.com/1668687/40572277-78a93e40-60b0-11e8-90d8-4c09ffcea0f1.png">

**Comment by sagivf** [comment]
Oh cool, Not sure what the difference between "squash and merge" vs " rebase and merge". I'll investigate. So are you for it?

**Comment by sagivf** [comment]
In my last place of worked we just rebased our branches on to master before the pull request and that way master could just fast forward. I agree that in an open source project like this if more then one person is working on a branch or if there is a big divergence rebase can be a bit of a pain.
So I would say try to rebase on to master when easy (you can always abort or reset hard).
