### ISSUE TITLE
Rationale?

### ISSUE THREAD

**Issue by ChrisTalman** [RebirthDB/rebirthdb-desktop#26]
Hey! From what I've heard, this project is intended to be the primary UI for Rebirth moving forward. However, I could not find any documentation explaining the rationale behind this project, or the technologies that it will be using. It'd be really useful to clarify these matters, and I hope the following questions serve to that end.

1. Does this replace the existing Web UI?
2. If so, why move away from the Web?
3. Will the Web UI continue to exist in any form?
4. Does the project use Electron?
5. What technologies does the project use? i.e. components, state, views, routing, CSS processing, bundling.
6. Has the project considered using TypeScript?

Personally, I've wanted to contribute to the Web UI in the past, but the technology stack put me off. If we have the chance to shake things up a little, it's important we move forward with a reasonable technology stack and end goal in mind. I hope this issue serves to help with that.

**Comment by oferitz** [comment]
Hey @ChrisTalman! Those are certainly valid points that have already been discussed thoroughly [here](https://spectrum.chat/?t=467d3f97-64c0-4131-8371-08ef3e5cb783). I Think @thelinuxlich can elaborate and explain points 1-3 better than me.

As for the other points:

4. Yes. the project use Electron and will make extensive use of Node.js capabilities.
5. **Components, Views:** React
**Routing**: React router
**State**: we feel it's too early and unnecessary to introduce state management solution at this stage, although we are getting close to the point when we will have to.
**CSS**: We choose to go with CSS in JS powered by [emotion](https://emotion.sh/)
**Bundling**: Webpack
**Testing**: Jest
**Code style and linting**: Prettier and StandardJS

6. We considered TypeScript against the knowledge and the previous experience of the people who were willing to step in when this project started and decided not to go with TypeScript. Having said that we are experimenting with a [TypeScript based driver](https://github.com/ronzeidman/rebirthdbts) as a replacement for the official driver that we are currently using. The driver has very important part in this project so if you are a TypeScript fan you should defiantly take a look at this project. 

I apologise that i haven't found the time yet to put all of this into Docs or README (we have an open issue about it #10),  i would love to see people stepping in and helping with this effort, specially with placing a proper README, as english is not my native language and i'll probably will do very crappy job, slaughtering every grammar rule in the way, while trying to write those by myself.

Finally i think it is a great opportunity and good timing to join the effort of building this exciting project! And i hope you will join us.

**Comment by thelinuxlich** [comment]
About points 1-3:

The existing codebase is written in ancient Coffeescript code + old versions of Backbone and Bluebird(which also introduced build problems for the whole database repository). So instead of just splitting the web UI into its own project, we've got some heroes here willing to rewrite the UI using the latest of the greatest in JS tech. Electron was chosen because we don't want the database anymore spawning a web server and the official javascript driver had a unofficial api specifically to communicate with the internal REST Api, thus another dependency we are axing in favor of rethinkdbdash or the new typescript driver.

**Comment by thelinuxlich** [comment]
We will add a issue template to notify users that this place is dedicated to bugs and features, if you have any questions, please ask in our community channel: https://spectrum.chat/rebirthdb

**Comment by ChrisTalman** [comment]
Apologies for my delay. Thanks for your responses.

My reason for raising this issue was to get a sense of whether the technology stack and goals were still in flux, and to contribute to the discussion if they were. It seems that everything is set in stone at this point.

Although React might not have been my preference, if I come to use Rebirth in the future and notice a useful feature to add to the UI (as has been my experience with the Rethink Web UI), hopefully the development experience will be accessible.

As an aside, I'd certainly recommend trying out TypeScript, if you haven't already. It makes a project a lot more maintainable, while at the same time remaining very much JavaScript.

Good luck @oferitz, hope you have fun on this project. 😃
